### ISSUE TITLE
new sql err: pt summary medical problem widget

### ISSUE THREAD

**Issue by htuck** [LibreEHR/LibreEHR#100]
When patient record summary displays, 'Medical Problems' widget at lower right shows up with errors:
	ERROR: query failed: SELECT `date` FROM `lists_touch` WHERE pid=? AND type=?
	Error: Table 'libreehr_socrates.lists_touch' doesn't exist
	/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/library/lists.inc at 127:sqlQuery
	/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/patient_file/summary/stats.php at 170:getListTouch(14364,medical_problem)

![medicalwidget](https://cloud.githubusercontent.com/assets/8339489/17718365/647cefac-63c8-11e6-9185-5a5e1a1693cb.png)

**Comment by aethelwulffe** [comment]
What is a libreehr_socrates?

**Comment by tmccormi** [comment]
It's just the test database we are using for this.

**Comment by htuck** [comment]
Appears to be fixed. Closing.
