### ISSUE TITLE
new sql err: patient/ client search

### ISSUE THREAD

**Issue by htuck** [LibreEHR/LibreEHR#101]
Patient/ Client search - 
	had used that form for 'create new patient' and it worked fine
BUT- entered a known good first name in 'first name' field then 'search' ->

	Input array has 1 params, does not match query: 'SELECT *, DATE_FORMAT(DOB,'%m/%d/%Y') as DOB_TS FROM patient_data WHERE ORDER BY lname ASC, fname ASC LIMIT 0, 100'
	ERROR: query failed: SELECT *, DATE_FORMAT(DOB,'%m/%d/%Y') as DOB_TS FROM patient_data WHERE ORDER BY lname ASC, fname ASC LIMIT 0, 100
	/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/main/finder/patient_select.php at 204:sqlStatement

entered both 2 partial first and last names, and full known good first and last names; got same error:

 Input array has 2 params, does not match query: 'SELECT *, DATE_FORMAT(DOB,'%m/%d/%Y') as DOB_TS FROM patient_data WHERE ORDER BY lname ASC, fname ASC LIMIT 0, 100'
ERROR: query failed: SELECT *, DATE_FORMAT(DOB,'%m/%d/%Y') as DOB_TS FROM patient_data WHERE ORDER BY lname ASC, fname ASC LIMIT 0, 100

/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/main/finder/patient_select.php at 204:sqlStatement

**Comment by teryhill** [comment]
Yep that's a bug that we are waiting on Ken to address

**Comment by teryhill** [comment]
@tony this is the same cause as #87

**Comment by tmccormi** [comment]
Yep, closing as duplicate
