### ISSUE TITLE
SQL upgrade fails

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#108]
Even if there is nothing to do, it should not fail...

**RENAME `openemr_module_vars` TO `libreehr_module_vars`
ERROR: query failed: RENAME `openemr_module_vars` TO `libreehr_module_vars`

Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`openemr_module_vars` TO `libreehr_module_vars`' at line 1**

/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/library/sql_upgrade_fx.php at 504:sqlStatement
/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/sql_upgrade.php at 55:upgradeFromSqlFile(0_0_1-to-1_0_0_upgrade.sql)

**Comment by aethelwulffe** [comment]
Here...I am wrapping it in them tagses #EndIf

**Comment by aethelwulffe** [comment]
We have a merge here, is this issue closed?

**Comment by tmccormi** [comment]
I have not tested it yet for final, yet

Tony

-- 
Please be aware that e-mail communication can be intercepted in 
transmission or misdirected. Please consider communicating any sensitive 
information by telephone.  The information contained in this message may be 
privileged and confidential. If you are NOT the intended recipient, please 
notify the sender immediately with a copy to hipaa-security@mrsb-ltd.com and 
destroy this message.

**Comment by aethelwulffe** [comment]
I have tested this a multitude of times.  Closing issue
