### ISSUE TITLE
latest download of code calendar will not come up

### ISSUE THREAD

**Issue by teryhill** [LibreEHR/LibreEHR#113]
I get  "There were to many redirects" on the screen and the calendar will not come up. Nothing in the PHP error log

Tabs titles are also not changing. @Tony has the CSS changes caused an issue?

**Comment by teryhill** [comment]
Nope it is not the @tony commit.  The labels issue cleared on screen refresh. Still getting the "There were to many redirects" . 
![redirect](https://cloud.githubusercontent.com/assets/4655366/17974011/797392e4-6ab2-11e6-8b4e-9a72ab3528d9.PNG)
Can some one else check and see if they get the same problem @aethelwulffe

**Comment by tmccormi** [comment]
It's working fine on my local install. (ubuntu 14.04)

**Comment by teryhill** [comment]
Any Ideas why it would be doing this on my windows system?

@aethelwulffe can you check it on windows

**Comment by aethelwulffe** [comment]
Lemme pull down a freshie and give it a go.

Just got in from doing cabinets, so I still gotta pour some hot coffee 
to cool down with.

**Comment by aethelwulffe** [comment]
Just did a total fresh install.

Everything worked just fine.

Created patients, appointments, switched the calendar back and forth, 
added users.

**Comment by teryhill** [comment]
must be on my system closing issue
