### ISSUE TITLE
Update Logo graphics to be more "in-line" with LibreHealth

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#114]
Update's to the logo and graphics should reflect some commonality with the LibreHealth project for marketing reasons.   Sara created a couple of possible graphics

![libreehr-sheild2](https://cloud.githubusercontent.com/assets/285835/17976726/99ffe594-6aa3-11e6-9604-650a8a240608.png)

![libreehr-sheild](https://cloud.githubusercontent.com/assets/285835/17976728/9ba882de-6aa3-11e6-8844-72c223ff3608.png)

She provided them as vector graphics as well in EPS and AI formats.

**Comment by aethelwulffe** [comment]
Looks good to ME!

**Comment by aethelwulffe** [comment]
Hate the burnt orange stuff, but that's what we pay for solidarity, let it be so!  (I want that put on my "collaboarative scorecard" tho....)

**Comment by teryhill** [comment]
Gooooo Vol's

**Comment by aethelwulffe** [comment]
Hook'em Horns!
![sticky_logo](https://cloud.githubusercontent.com/assets/553751/17986813/a13a39c6-6aea-11e6-82d0-dffb8c74272e.png)

**Comment by aethelwulffe** [comment]
BTW, you don't need the apostrophe in Vols.  You just need one of those 
big fingers to point in the air, or two big fingers if you are rooting 
for University of Texas.

It is somewhat disconcerting that the burnt orange color is also the 
theme for Bill Miller's Barbecue, and that causes other associations in 
my mind.  Barbecue, BM, and Slash And Burn do go together nicely though.

**Comment by aethelwulffe** [comment]
Like so:
![untitled](https://cloud.githubusercontent.com/assets/553751/17988971/e6f86fb6-6af7-11e6-9388-81227c067517.png)

**Comment by aethelwulffe** [comment]
Might just have to pick one of Sara's choices as an interim stand-in until LibreHealth makes up it's collective mind.

**Comment by aethelwulffe** [comment]
The orange turns me off a bit, but hey, I just painted a whole waiting room turquoise and hunter green...with a wavy line...against my better judgement....and everyone else loves it...even without all the little houses and stuff for the mural.

**Comment by tmccormi** [comment]
Also updated the web page and github site logo
