### ISSUE TITLE
Change to Flow board originally by MDsupport

### ISSUE THREAD

**Issue by teryhill** [LibreEHR/LibreEHR#133]
Change to Flow board originally by MDsupport

**Comment by teryhill** [comment]
Keep this around for a while

**Comment by aethelwulffe** [comment]
Wanna add the close button to this issue?

**Comment by teryhill** [comment]
Got one more thing I want to send up having to do with the flow board. (I think it will be well received)

**Comment by aethelwulffe** [comment]
Oh Goodygoodygoody!

**Comment by teryhill** [comment]
Taking longer that expected closing this will open another one later for the enhancements
