### ISSUE TITLE
added epsdky appointment changes to demographics

### ISSUE THREAD

**Issue by teryhill** [LibreEHR/LibreEHR#136]
This was originally done by epsdky it adds some very neat visual aids to seeing the appointments in the demographcs screen

**Comment by tmccormi** [comment]
Are there some screenshots of this, It sounds very odd to me from the description.

**Comment by teryhill** [comment]
These are the colors I selected.

![apptsc1](https://cloud.githubusercontent.com/assets/4655366/18072130/b10eead0-6e29-11e6-9cdc-6b1f66699d3c.PNG)

**Comment by aethelwulffe** [comment]
So, it applies the color categorization to the patient appointment dropdown in demographics.  This seems to be a consistency improvement to me.
