### ISSUE TITLE
Dated Reminder User List not alpha

### ISSUE THREAD

**Issue by aethelwulffe** [LibreEHR/LibreEHR#144]
Dated reminder addressee selector does not alphabetize.  It also fails to restrict to actual local active users.  It's size is restricted to displaying 5 at a time (which is not comfortable when there are dozens of users). List of reminders is limited to 5 (not sufficient for heavy use).

**Comment by tmccormi** [comment]
I would add... and it view and use is OFF by default...

**Comment by aethelwulffe** [comment]
Except that it's one of the best tools in the system.

**Comment by aethelwulffe** [comment]
Not wanting to start an argument, but if this was off, I would say that you should turn off ALL features by default.  The dated reminders, and the ability to send a work-list to people (and your self) that can be checked off and the like is vital.  This is the feature that cut email, confusion, forgotten advisories, and PHI violations down to a fraction of what it was around here.

**Comment by aethelwulffe** [comment]
One way or another, I would like to massively expand this system, or participate in a new message system that has the same features and options.
  I would like to see group addresses, or "teams", such as "Billing", "Administration", "Nursing" etc...
  I would like to add more hooks to new_patient (form_encounter) to send configurable reminders when a particular type of category of service is used (event, disclosure etc...)
  It would be good if something like this picked up a work list from denied claims and the like as well.

Just about anything you can think of that a work list is helpful for can be done with this, and pretty efficiently in terms of two-way communication.  My own reminders mostly start with "Hey, Art, fix...".  Viola; an instant bug tracker system that any of my users can access and check.

**Comment by tmccormi** [comment]
Dated reminders iz kewl. Just needs a bit of UI tweaking and some way to use it from other places (like Phy Orders for Encounter or Pt Demo summary page)  or as a separate menu item that pops a fancybox.
