### ISSUE TITLE
No "close" button on Flow Board tab

### ISSUE THREAD

**Issue by kchapple** [LibreEHR/LibreEHR#156]
When the Flow Board is open there is no button it's tab to close it. 
![screen shot 2016-09-09 at 9 40 29 am](https://cloud.githubusercontent.com/assets/271809/18388930/9853d1ae-7671-11e6-820d-d4de8f45e6e1.png)

**Comment by teryhill** [comment]
the same thing happens with the calendar also.

**Comment by tmccormi** [comment]
This is true of Calendar and Message Center as well.

**Comment by aethelwulffe** [comment]
pull #176
