### ISSUE TITLE
claims table format error

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#167]
The claims table is not being created on setup. (silent fail)

See attached.   Is anyone else getting this?  @aethelwulffe ?

![claims-table-error](https://cloud.githubusercontent.com/assets/285835/18490045/2a9f7392-79b5-11e6-8896-ede85d77c281.png)

mysql  Ver 14.14 Distrib 5.5.50,

**Comment by aethelwulffe** [comment]
I think this will be OK:
`    $inc_version = sqlQuery("SELECT MAX(version)+1 FROM claims ".
      "WHERE patient_id = '$patient_id' ".
      "AND encounter_id = '$encounter_id';");`

**Comment by aethelwulffe** [comment]
changing everything.  I am a sleepy idiot.
In testing mode, but I gotta spin one up.  Seem to be about a million varieties and styles of query running functions in that library.  I decided to assign a variable, but I could also use

**Comment by aethelwulffe** [comment]
I have a change if this doesn't work.  This was integrated on the "fast forward merge" model.

**Comment by tmccormi** [comment]
Closing this.  You solution is fine
