### ISSUE TITLE
README.md, COPYRIGHT and LICENSE files need updates

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#170]
Need to rename license.txt to gpl_license.txt and and add mpl_licence.txt and modify the the file
COPYRIGHT_AND_LICENSE accordingly

README.md needs beefing up.

**Comment by tmccormi** [comment]
Proposed change to README.md

**Welcome to LibreEHR!!!**

LibeEHR is a Free and Open Source electronic health records and
medical practice management application. 

The mission of LibreEHR.org is to help provide high quality medical care to all people, regardless of race, socioeconomic status or geographic location, by giving medical practices and clinics across the globe access to medical software, free of charge.

That same software is designed to save clinics both time and money, which gives practitioners more time to spend with individual patients, thereby affording patients with higher quality care.

We are current and former contributors to OpenEMR and thank that community for years of hard work. We intend to honor that legacy by allowing this new community to leverage the good things in OpenEMR, share what we create and not be afraid to break backward compatibility in the name of forward progress and modern development models.

We will be collabating closely with the LibreHealth Project [LibreHealth.io](http://LibreHealth.io), a fork of OpenMRS with similar goals.   

Our project is primarily Licensed under Mozilla Public License Version 2

Code inherited the original OpenEMR project is licensed under GPL 2 or Higher.

**Comment by teryhill** [comment]
Looks good. You just may want to re-read the last line, looks like it is missing something.

**Comment by aethelwulffe** [comment]
Code inherited the original OpenEMR

to: Code inherited from + (the original project || OpenEMR || the source 
project || the source project; OpenEMR || etc...)

add "from" and something else.

**Comment by tmccormi** [comment]
Pull request is ready for review
