### ISSUE TITLE
Modules>Manage Modules broken

### ISSUE THREAD

**Issue by aethelwulffe** [LibreEHR/LibreEHR#178]
Modules/manage modules:
PHP Fatal error:  Uncaught RuntimeException: Unable to load ZF2. Run `php composer.phar install` or define a ZF2_PATH environment variable. in C:\\xampp\\htdocs\\LibreEHR\\interface\\modules\\zend_modules\\init_autoloader.php:53\nStack trace:\n#0 C:\\xampp\\htdocs\\LibreEHR\\interface\\modules\\zend_modules\\public\\index.php(42): require()\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\LibreEHR\\interface\\modules\\zend_modules\\init_autoloader.php on line 53, referer: http://localhost/LibreEHR/interface/main/tabs/main.php?url=main_info.php

**Comment by tmccormi** [comment]
separate issues for separate bugs please.

**Comment by aethelwulffe** [comment]
Sure, but not completely sure that the cause isn't the same issue.

**Comment by tmccormi** [comment]
This is broken, because you can't manage the modules unless you install ZEND App Framework first (separately) and configure LibreEHR to point to it.

**Comment by tmccormi** [comment]
Perhaps, just an "If Exists" around the menu item?

**Comment by teryhill** [comment]
Why not just remove it from the menu for now?

**Comment by tmccormi** [comment]
Well,
   If we are not going to support the care modules at all via Zend that sure we should remove all of it.   I wasn't willing to go that far yet.   Are any of the Zend based things completely local install or do they all require ZHH external services?

**Comment by teryhill** [comment]
I think the care module is. The new patient portal will create a CCDA with out ZHH, send Immunizations, and handle messages from the patient. Let's not remove the zend stuff just the menu item.

**Comment by aethelwulffe** [comment]
pull request in.

**Comment by aethelwulffe** [comment]
Release candidate is up.  Closing issue and milestone.
