### ISSUE TITLE
sl_eob_search error

### ISSUE THREAD

**Issue by aethelwulffe** [LibreEHR/LibreEHR#186]
sl_eob_search.php
line 88 Menu item "Posting"
breaks here:
global $STMT_TEMP_FILE_PDF;
$pdf =& new Cezpdf('LETTER');//pdf creation starts <breaks here line 88
Test with FEES>POSTING

**Comment by aethelwulffe** [comment]
This is the last bug that does not have a commit against it.

**Comment by teryhill** [comment]
What is the error? Is the PDF library's still there?

**Comment by aethelwulffe** [comment]
Yes, the file is still there.
  Error is related to "NEW".
[Mon Sep 19 13:01:36.985089 2016] [:error] [pid 7120:tid 1792] [client ::1:65119] PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in C:\\xampp\\htdocs\\LibreEHR\\interface\\billing\\sl_eob_search.php on line 88, referer: http://localhost/LibreEHR/interface/main/tabs/main.php?url=main_info.php

**Comment by aethelwulffe** [comment]
In php7 the assignment of variables by reference is deprecated.  There is nothing wrong with the code, it is just meaningless to php7.

**Comment by teryhill** [comment]
take out the & and see if that fixes it for PHP7

**Comment by aethelwulffe** [comment]
I removed the &.
Now it works.
I have a pull in already.

**Comment by aethelwulffe** [comment]
@teryhill Looking back, the deprecation warning has been popping up since PHP5 came on the scene.  The project was ignoring this stuff for a very very long time.

**Comment by aethelwulffe** [comment]
I checked this out with NetBeans (which I don't use).  It doesn't give any warnings about it.
