### ISSUE TITLE
Globals Navigation Menu selection can go

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#190]
No need to select what kind of menu to use anymore

![navigation](https://cloud.githubusercontent.com/assets/285835/18651641/59f6b5d0-7e81-11e6-9de6-de5e6749e72a.png)

**Comment by teryhill** [comment]
The width is set as a default of 150 (if it is empty) in main_screen.php and used in main_title.php. I would suggest leaving it in those files until we are sure we can jerk those programs.

**Comment by tmccormi** [comment]
We can just hard code it and drop the option entry

**Comment by teryhill** [comment]
00104: $nav_area_width = '130';
00105: if (!empty($GLOBALS['gbl_nav_area_width'])) $nav_area_width = $GLOBALS['gbl_nav_area_width'];

**Comment by teryhill** [comment]
all done?
