### ISSUE TITLE
Referance to External Data in the patient Demographics screen

### ISSUE THREAD

**Issue by teryhill** [LibreEHR/LibreEHR#193]
Shouldn't this be taken out ?

![externaldata](https://cloud.githubusercontent.com/assets/4655366/18653240/8cdcaa8e-7ea6-11e6-81b6-63668ffcc66d.PNG)

**Comment by tmccormi** [comment]
What's it for?   I've never noticed that one...

**Comment by teryhill** [comment]
It's a hook for some yet to come stuff .

**Comment by teryhill** [comment]
merged
