### ISSUE TITLE
Merge Release Candidate Branch into Master

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#202]
Merge and TAG as REL_1_0_0 when accepted by team.

**Comment by tmccormi** [comment]
Once merged and tagged create a Development_101 branch and set it as the base branch for pull requests.

**Comment by aethelwulffe** [comment]
Accepted

**Comment by tmccormi** [comment]
Re Opening this.  Since RC1 was not actually tested before excitement caused merge. Going to remove the release tag.

**Comment by aethelwulffe** [comment]
Tested it...poorly.  Opened it up, started clicking tabs (which appeared 
to work, because I didn't look before clicking in windowed mode.  Real 
crappy testing.  Sorry.  Figured minor changes...Meh.

**Comment by aethelwulffe** [comment]
I was REALLY EXCITED THOUGH:'(

**Comment by tmccormi** [comment]
So test against MASTER branch and do pull requests for any fixes against master (you'll need to manually select the 'master' branch when doing the request.

**Comment by tmccormi** [comment]
I am ready to officially stamp the release out after I add Art's acknowledgement entry and merge the last minute ICD9 change

**Comment by tmccormi** [comment]
To git@github.com:LibreEHR/LibreEHR.git
   80e58c7..a4bfd87  master -> master
 * [new tag]         REL-1_0_0 -> REL-1_0_0
tony@dragonfire:/opt/gitrepos/LibreEHR (master)$ gitlog
a4bfd87 Roll Version to release 1.0.0
