### ISSUE TITLE
global nav area removal broke EHR

### ISSUE THREAD

**Issue by aethelwulffe** [LibreEHR/LibreEHR#203]
Reproducible.
Install LibreEHR.  Menu is messed up big-time, like every version of the navigation system we have ever had, from "original", "Tree", and Tabs all at one time.  No sliding menu though!
Reverted removal of Modules change.  No effect.  Reverted Global nav area change...fixed.
Should look at this again.
Will re-create windows installer after.
I go sleep.

**Comment by aethelwulffe** [comment]
---------- Find in Files ----------
> Searching for the string '$nav_area_width'...
C:\AlphaFiles\bidenis\REPOS\LibreEHR\interface\main\main_screen.php(104,1): $nav_area_width = '130';
C:\AlphaFiles\bidenis\REPOS\LibreEHR\interface\main\main_screen.php(158,38):      <frameset cols='<?php echo attr($nav_area_width) . ',*'; ?>' id='fsbody' frameborder='1' border='4' framespacing='4'>
C:\AlphaFiles\bidenis\REPOS\LibreEHR\interface\main\main_screen.php(165,46):      <frameset cols='<?php echo  '*,' . attr($nav_area_width); ?>' id='fsbody' frameborder='1' border='4' framespacing='4'>
C:\AlphaFiles\bidenis\REPOS\LibreEHR\interface\main\main_screen.php(177,33): <frameset cols='<?php echo attr($nav_area_width); ?>,*' id='fsbody' frameborder='1' border='4' framespacing='4' onunload='imclosing()'>

More places use the variable $nav_area_width

**Comment by aethelwulffe** [comment]
RETREAT!  RETREAT!

**Comment by tmccormi** [comment]
Merged.  Test with Master please

**Comment by aethelwulffe** [comment]
Exactly the same.
Maybe I didn't pull from the right branch or something.
Maybe that wasn't the issue.

**Comment by teryhill** [comment]
Check and make sure you have the correct code. The only other thing was the other variable that was removed.

**Comment by teryhill** [comment]
It is probably the other commit. I will do some checking

**Comment by teryhill** [comment]
set ($GLOBALS['concurrent_layout']) to 3 in the globals.php

**Comment by aethelwulffe** [comment]
Did.  No change.  Maybe that is because the user preferences are now overriding it, and I don't have an interface to change that directly.  I'll look, but I am really running out of time today.

**Comment by teryhill** [comment]
I will work on it as soon as I get back

**Comment by teryhill** [comment]
See if the reversal does it

**Comment by tmccormi** [comment]
Is this issue resolved @teryhill

**Comment by teryhill** [comment]
I just reverted the code and sent up a pr for it. It is going to take a lot to pull it out of the files that are affected.
I have not tested

**Comment by aethelwulffe** [comment]
Built an installer package off of master/New_Documentation, a branch that was created this morning and is currently ahead of master.
Installer worked perfectly, documentation worked perfectly, and the EHR seems to be fixed of the menu woes.

**Comment by aethelwulffe** [comment]
Calling this resolved.  Closing.  Tests look great on PHP7 and Windows.
