### ISSUE TITLE
Create development 101 branch and make it default

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#205]
This branch is where all new development for the NEXT release should be branched from.

I will update it with any changes we make to the master at release time.

**Comment by tmccormi** [comment]
So by default cloning the repo now pulls developent_101.   This is great for devs, but maybe not for "users" that would install the release from master ...   Just thinking out loud.

git clone git@github.com:LibreEHR/LibreEHR.git libre-dev
Cloning into 'libre-dev'...
remote: Counting objects: 54349, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 54349 (delta 5), reused 3 (delta 3), pack-reused 54331
Receiving objects: 100% (54349/54349), 188.33 MiB | 4.80 MiB/s, done.
Resolving deltas: 100% (35968/35968), done.
Checking connectivity... done.
tony@dragonfire:/opt/gitrepos$ cd libre-dev/
tony@dragonfire:/opt/gitrepos/libre-dev (development_101)$ cd ..

**Comment by tmccormi** [comment]
This is how you make the clone pull master as the HEAD ref
`git clone -b master git@github.com:LibreEHR/LibreEHR.git
`

**Comment by aethelwulffe** [comment]
No, that's how you do it.  
I arrange muticolored icons on a modified copy of github for windows with totally different terminology.
That was what I had to do to invent a precise terminology (which let me finally use this stuff).  Testing rel can...heavily...before I post again

**Comment by tmccormi** [comment]
THis issue is closed.
