### ISSUE TITLE
Acknowledgements missing Art

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#208]
Art Eaton / Suncoast does not appear to be listed as a contributor in the file acknowledge_license_cert.html.

Is that an oversight or intentional?

**Comment by aethelwulffe** [comment]
Is there any value to that?  If so, by all means, add us on.

**Comment by tmccormi** [comment]
I guess should also ask, what did Sam Bowen contribute to LibreEHR?

**Comment by aethelwulffe** [comment]
Inspiration?

Honestly, if such comes to pass, one might say my efforts are funded 
by.  Should that come to pass.

**Comment by tmccormi** [comment]
I'll add you, but I need some basic info. like which email addy you want to use and should SunCoast be listed to just you?

**Comment by aethelwulffe** [comment]
Art@SunCoastConnection.com  SunCoast Connection Inc. would be good.

**Comment by tmccormi** [comment]
Done.
