### ISSUE TITLE
SQL upgrade fails 0_0_1 to 1_0_0

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#218]
ERROR: query failed: DROP COLUMN `cmsportal_login`

Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COLUMN `cmsportal_login`' at line 1

And this fails if your run SQL Upgrade a second time after the column has been dropped
# IfColumn transactions

 ALTER TABLE `users` DROP COLUMN `ssi_relayhealth`;
# EndIf

**Comment by tmccormi** [comment]
see also #223

**Comment by aethelwulffe** [comment]
if (exists (SELECT * FROM information_schema.COLUMNS WHERE TABLE_NAME = 'patient_data' AND COLUMN_NAME = 'cmsportal_login'))
begin
    ALTER TABLE patient_data  DROP COLUMN `cmsportal_login`;
end

The above will only work if this is running as root.

**Comment by aethelwulffe** [comment]
Got a fix.  IfColumn did not have both the table and column arguments in query just before this one..
Checking whole file now
