### ISSUE TITLE
Document Categories - EDIT not working

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#220]
Administration->Practice->Documents->EDIT Categories

Does not present the Tree for editing.   tested on release demo site.

![edit-doc-categories-broken](https://cloud.githubusercontent.com/assets/285835/19095091/a805dc88-8a48-11e6-91fb-0f20a939e4c7.png)

**Comment by tmccormi** [comment]
Treemenu not defined

![practice-document-error](https://cloud.githubusercontent.com/assets/285835/19095293/d00a2ad0-8a49-11e6-8f8a-2de655291018.png)

**Comment by tmccormi** [comment]
Did not intend to close this one

**Comment by tmccormi** [comment]
Anyone have any thoughts here.  Nothing obvious to me.

**Comment by aethelwulffe** [comment]
Well, we know where that menu is defined, and where the libraries (that were moved I think) are.  I will go looking.

**Comment by aethelwulffe** [comment]
CategoryTreeMenu.js is not in the root directory.  DocumentTreeMenu.js still is.

**Comment by tmccormi** [comment]
There is not TreeMenu.js in base openemr either, only DocumentTree, I assumed it was a rename.  There is no Treemenu,js in either code base at all.

**Comment by tmccormi** [comment]
did someone rename it or something?

**Comment by aethelwulffe** [comment]
BPUC has both...look for blame.  I am dumping it in to test.

**Comment by aethelwulffe** [comment]
Dumping in CategoryTreeMenu.js that is.

**Comment by tmccormi** [comment]
There is no such thing as 
tony@dragonfire:/opt/gitrepos/LibreEHR (master)$ find . -name CategoryTree\* -print
./library/classes/CategoryTree.class.php

**Comment by aethelwulffe** [comment]
Yes, that fixes it.  Pushing to a branch here in a minute.

**Comment by aethelwulffe** [comment]
Want on dev or master?

**Comment by tmccormi** [comment]
Dev is fine, you should be about to undelete from the repo (versus) an new copy ..
but whatever  works

**Comment by aethelwulffe** [comment]
I am an idiot.  This did NOT fix this.  I totally misunderstood the issue.

**Comment by aethelwulffe** [comment]
I see that something is looking for these libraries at library/js instead of the root, and they were not there.  Also, this seems to have issues:
<?php require_once($GLOBALS['srcdir'].'/js/DocumentTreeMenu.js');?>

**Comment by aethelwulffe** [comment]
OK...bigtime boo-boos going on there.  Documenting as I go through.
First:  No Administration/Other/Calendar.  That means we have no way of clearing the SMARTY cache.  This seems like a related issue, and I can't clear the cache...cause the menu item isn't there...unless I delete manually.
Next:  Treemenu might be css related.
Next:  Replaced jquery.1.3.2.js with jquery-1.7.2.min.js (newer is available) and lots of errors went away off the console...not a fix yet.
Something goofy in the html template where it calls the library.

**Comment by aethelwulffe** [comment]
GOT IT!
DocumentTreeMenu.js not being called properly.
`<script type="text/javascript" src="/LibreEHR/interface/../library/js/DocumentTreeMenu.js"></script>`
instead of php in the template.

**Comment by aethelwulffe** [comment]
This fix is confirmed in broad daylight.  Pull request awaiting.

**Comment by tmccormi** [comment]
I merged this to master and tried a new install on my 14.04 LTS.  No Joy  it's doing the same exact thing

![docatgeditrel100](https://cloud.githubusercontent.com/assets/285835/19532430/7e206312-95f0-11e6-806e-627f808ba467.png)
![treemen-notdef](https://cloud.githubusercontent.com/assets/285835/19532433/80ee2e12-95f0-11e6-9ca3-079bc83fee58.png)

**Comment by tmccormi** [comment]
The files are in the install in the 'root' location

```
tony@dragonfire:/var/www/LibreEHR$ ls
acknowledge_license_cert.html  composer.lock              favicon.ico          interface         phpunit.xml      templates
acknowledge_license_cert.rtf   contrib                    gacl                 ippf_upgrade.php  README.md        Tests
acl_setup.php                  controller.php             GITSOURCEBRANCH.log  library           README.rtf       version.php
acl_upgrade.php                controllers                gpl_license.txt      license.txt       setup.php
admin.php                      COPYRIGHT_AND_LICENSE.txt  images               modules           sites
CategoryTreeMenu.js            custom                     includes             mpl_license.txt   sql
ccr                            Documentation              index.php            myportal          sql_patch.php
composer.json                  DocumentTreeMenu.js        INSTALL              patients          sql_upgrade.php

```

**Comment by aethelwulffe** [comment]
Well, they are there now. #252
