### ISSUE TITLE
Letter Pop up..  White Screen version 1.0.0

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#228]
[Thu Oct 06 23:19:40.802596 2016] [:error] [pid 20043] [client 37.228.227.191:6948] PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /opt/ehr/interface/patient_file/letter.php on line 146, referer: https://ehr.librehealth.io/interface/main/tabs/main.php?url=main_info.php

**Comment by aethelwulffe** [comment]
We already knew that ezpdf has issues in this environment.

**Comment by teryhill** [comment]
Sent up a fix

**Comment by aethelwulffe** [comment]
Sent up additional fix across the code base.
#230

**Comment by tmccormi** [comment]
This can be closed I assume
