### ISSUE TITLE
Unable to save new user after upgrade on demo site (more mysql strict issues)

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#235]
Trie to add a user called "doctor1" - on save got this error on screen
Failure during database access! Check server error log.

[Mon Oct 10 22:35:48.794873 2016] [:error] [pid 17907] [client 50.43.80.9:57689] Executing as user:libreehr Statement failed:insert into users set username = 'doctor1', password = 'NoLongerUsed', fname = 'Doc', mname = '', lname = 'One', federaltaxid = '1233441223', state_license_number = '', newcrop_user_role = '', physician_type = '', authorized = '1', info = 'The Doctor\r\npass=doctor1', federaldrugid = '', upin = '', npi  = '', taxonomy = '207Q00000X', facility_id = '3', specialty = '', see_auth = '3', cal_ui = '3', default_warehouse = '', irnpool = '', calendar = '1', pwd_expiration_date = ''**:Incorrect date value: '' for column 'pwd_expiration_date' at row** 1==>/opt/ehr/interface/usergroup/usergroup_admin.php at 271:update_password, referer: https://ehr.librehealth.io/interface/usergroup/usergroup_admin_add.php

**Comment by aethelwulffe** [comment]
Is the global for expiration period configured?  If it isn't enforced, this is one issue, if the code is demanding a date no matter what, it is another.

**Comment by tmccormi** [comment]
Not configured, code is trying to write "" but it should be NULL I think instead
![security-default](https://cloud.githubusercontent.com/assets/285835/19254117/5ba33f90-8f05-11e6-9c57-2e0115f92656.png)

**Comment by aethelwulffe** [comment]
Configured it, and saved the user "demouser" pass Phrase "LibreEHR rocks."

**Comment by aethelwulffe** [comment]
Worked.

**Comment by tmccormi** [comment]
So, still need to fix the unconfigured bug,

**Comment by aethelwulffe** [comment]
Ja.  Looking at the appointments at the moment.  I have until 830EST or so, then Bryan comes back to work...

**Comment by aethelwulffe** [comment]
Shall we revisit the calendar hack now, or is there another hot bug to fix?  I got 22 minutes.
