### ISSUE TITLE
Unable to add appointments on ehr.librehealth.io

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#236]
ERROR: insert failed: INSERT INTO libreehr_postcalendar_events ( pc_catid, pc_multiple, pc_aid, pc_pid, pc_title, pc_time, pc_hometext, pc_informant, pc_eventDate, pc_endDate, pc_duration, pc_recurrtype, pc_recurrspec, pc_startTime, pc_endTime, pc_alldayevent, pc_apptstatus, pc_prefcatid, pc_location, pc_eventstatus, pc_sharing, pc_facility,pc_billing_location,pc_room ) VALUES (?,?,?,?,?,NOW(),?,?,?,?,?,?,?,?,?,?,?,?,?,1,1,?,?,?)

Error: Incorrect integer value: '' for column 'pc_multiple' at row 1

/opt/ehr/library/encounter_events.inc.php at 332:sqlInsert
/opt/ehr/interface/main/calendar/add_edit_event.php at 123:InsertEvent(Array)
/opt/ehr/interface/main/calendar/add_edit_event.php at 584:InsertEventFull()

**Comment by tmccormi** [comment]
Mode is Strict ... 

SELECT @@sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by aethelwulffe** [comment]
No zero date kills a lot of stuff.  I think your user addition bug is also the same root issue.

**Comment by tmccormi** [comment]
Yes.  however I changed the setting to permissive, restarted mysql and still can't save.

 mysql> set sql_mode="";
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> SELECT @@sql_mode;
```
+------------+
| @@sql_mode |
+------------+
|            |
+------------+

```

**Comment by aethelwulffe** [comment]
Same error attempting to save an all day availability for a provider.
...Found the issue.  That was where we were trying to get rid of the autoincrement instead of fixing INNODB configuration properly.  Need to go back to autoincrement (because we don't have an index to start with), or do an additional workaround like I am about to try.
