### ISSUE TITLE
Remove IPPF SQL files

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#245]
Remove IPPF sql files
ippf_layout.sql
ippf_upgrade.sql

**Comment by teryhill** [comment]
Shouldn't it be remove IPPF period?

**Comment by tmccormi** [comment]
yes, but one thing at at time :-)

**Comment by teryhill** [comment]
But it must be in the correct order also

**Comment by tmccormi** [comment]
generally true, but since we don't support IPPF in this code at all it's fine to drop the sql now.

**Comment by aethelwulffe** [comment]
Then let's get the IPPF removal (and any references to USMC) into an issue.
