### ISSUE TITLE
New install fails (silently) to create facility table

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#246]
DROP TABLE IF EXISTS `facility`;
CREATE TABLE `facility` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(255) default NULL, 
  `alias varchar(60) default NULL,    **<--- NOTICE The missing back-tic**

  `phone` varchar(30) default NULL,
 etc ...

**Comment by teryhill** [comment]
I don't think there should be one at all

**Comment by tmccormi** [comment]
The actual database.sql using back-tics,  they don;t cut and paste into the markup for github well.   In anycase a pull request is in...
