### ISSUE TITLE
dev branch iframe is borked

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#249]
development_101 has some how gotten the Globals settings for iframe versus the old leftnav mixed up again.  I thought we temporarily fixed that.  But my new install/setup is badly broken.

![globals-nav-borked](https://cloud.githubusercontent.com/assets/285835/19877260/eac602c0-9f9a-11e6-9b40-0cee6592970b.png)

**Comment by teryhill** [comment]
it looks like 204 and 210 did not make it to the dev branch

**Comment by tmccormi** [comment]
good catch, that was right when we switch for master to dev during release ...
I'll cherry-pick them back.

Question: is no one else testing new installs from this branch.  This should have been caught sooner

**Comment by teryhill** [comment]
Lets see there's you , art and me  Ummm guess not. I fixed my install and was working on other issues. Sorry

**Comment by tmccormi** [comment]
yep, not placing blame ... need some automations ...
