### ISSUE TITLE
Database and version refactor

### ISSUE THREAD

**Issue by aethelwulffe** [LibreEHR/LibreEHR#47]
I have made a couple of pull requests dealing with /sql and the upgrade scripts.
I changed the version to 1.0.0, db=1, and made an sql upgrade file called 0.0.1_to_1.0.0 that includes most of the good stuff from the last two upgrade scripts.  I have left out the species and  theology bits, and dumped the county list for some random counties in an unknown state (which broke custom lists all over the place), and tossed a lot of other things like clickoptions conversions, old default data, and some odd scripts that allowed the creation of some users named "Barry" and others.

So:  What is the next step in making a fresh new upgrade system?

**Comment by tmccormi** [comment]
Take a look at the way it was handled in a recent green field laravel application we wrote (Aron wrote and I paid for).   https://github.com/mi-squared/volunteer-portal/tree/master/service/database/migrations

**Comment by aethelwulffe** [comment]
Review this please, and someone decide on a new issue/milestone/assignment on the "big Question" piece of this, then close it.  I think we have addressed the basic 1.0 level of this question.
