### ISSUE TITLE
Clean up application root directory.

### ISSUE THREAD

**Issue by aethelwulffe** [LibreEHR/LibreEHR#48]
We have lots of messy stuff in the application root directory.  I would like to see that, as a start, get moved somewhere appropriate.

**Comment by teryhill** [comment]
What about cleaning up all the js, jquery stuff with all the different versions

**Comment by aethelwulffe** [comment]
I figure hitting it in small pieces is a start.  Keeps the "issues" 
manageable.  Yes, the .js is a major need, and should be gone after.  
Should that mean that all .js should go in one pile, or just the min.js 
standard libraries?
