### ISSUE TITLE
Remove PhpMyAdmin

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#5]
Remove embedded PhpMyAdmin

**Comment by tmccormi** [comment]
I'll do this tonight.

**Comment by tmccormi** [comment]
I have the code done for this, just need to test it in the morning.

**Comment by aethelwulffe** [comment]
Did we already get the bookmarks taken out of the database?  Not seeing them...but...

**Comment by aethelwulffe** [comment]
Bookmark tables change between versions.  Not sure if the latest structure matches what is in the database.  If you want bookmarks, that would be part of the installation of PHPMyAdmin.

**Comment by tmccormi** [comment]
Completed
