### ISSUE TITLE
Syntax errors in Globals.inc.php 

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#52]
Unresolved merge conflicts in the latest commit ..

on or about line 261

    'online_support_link' => array(
      xl('Online Support Link'),
      'text',                           // data type
<<<<<<< HEAD
      'http://open-emr.org/',
=======
      'http://libreehr.github.io',
>>>>>>> refs/remotes/origin/master
      xl('URL for LibreEHR support.')

**Comment by tmccormi** [comment]
Sorry I missed that.  I can fix it real quick too...

**Comment by teryhill** [comment]
pu;; request is there

**Comment by tmccormi** [comment]
Close as duplicate ...

**Comment by aethelwulffe** [comment]
Sorry about that guys.
