### ISSUE TITLE
includes directory is useless

### ISSUE THREAD

**Issue by aethelwulffe** [LibreEHR/LibreEHR#61]
include_once(dirname(__FILE__) . "/../../includes/config.php");
This contains:
<?php
// Copyright (C) 2010 Rod Roark <rod@sunsetsystems.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

// $GLOBALS['OE_SITE_DIR'] is set in globals.php.
require_once $GLOBALS['OE_SITE_DIR'] . "/config.php";
?>
This is stupid.  Either we use this directory or get rid of it.  Which one?  Please Vote.

**Comment by tmccormi** [comment]
That is left over from legacy.   Needs to be refactored.  is config.php actually used for anything anymore

**Comment by aethelwulffe** [comment]
This was dropped with #63
