### ISSUE TITLE
Remove adLDAP

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#68]
This was offered on OpenEMR..  another good thing to clean out
remove adLDAP from library
D library/adldap/README.txt (9)
D library/adldap/adLDAP.php (725)
D library/adldap/adLDAP_auth.inc (261)
D library/adldap/adLDAP_conf.inc (24)
D library/adldap/adLDAP_sync.php (182)
D library/adldap/adLDAP_sync.sh (9)

**Comment by aethelwulffe** [comment]
Note that there is a lot of total junk in adodb.
files like "chris.php" and others that start with localhost db connections, and the string 'C0yote71' in them are next on the chopping block.  What do we actually need out of the adodb directory?

**Comment by tmccormi** [comment]
we could ditch adodb and use the current standard libraries instead and use PDO

**Comment by aethelwulffe** [comment]
Please!

for cr@p's sake, please give the d@mn project PDO.  Pretty. Freaking. 
Please.

How many times do I hear "Well, if we were just using PDO...."

**Comment by aethelwulffe** [comment]
http://tonylandis.com/php/adodb-pdo-convert-refactor-code/
This is what I have had bookmarked since the day it was posted.
Somewhat hackish, yes, but perfectly legitimate.

**Comment by tmccormi** [comment]
looks like a good start.  ALL sql access should be going through our own wrapper in order for logging to work, so it should not be toooooo hard tod directly convert the calls to PDO
