### ISSUE TITLE
ByteBugs

### ISSUE THREAD

**Issue by aethelwulffe** [LibreEHR/LibreEHR#73]
List of irritations, minor bugs, and personal peeves:

- [ ] Stray html and header tags everywhere.  In interface alone, there are 350 html opening tags.  Most all, if not all of these are seen as a second opening tag by time php makes a page.

- [x] Unused tables.

**Comment by aethelwulffe** [comment]
How many times should the code have the following string: `<html>`?

**Comment by teryhill** [comment]
I thought <html> started and </html> ended. However I am not that good at programming iI just kinda HACK

**Comment by aethelwulffe** [comment]
Open up, say, a patient note form.  Now view the source of the form.  You will notice lots of red references;  the first one being a stray opening html tag.   The issue is that all this stuff is effectively wrapped or included in other stuff, and that happens inside an existing html tag.   Then inside one of those, the tag is opened again, which is ignored.  Then it is closed, which is not, then.....

**Comment by aethelwulffe** [comment]
Doing good on dead table stuff.
