### ISSUE TITLE
Opening a Patient Demo Screen creates a Frame Tab "Unknown"

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#85]
It briefly says "New" and then changes to "unknown"

![unknown-frame-tab](https://cloud.githubusercontent.com/assets/285835/17679901/7ce8f35a-62f2-11e6-8ba3-395a09f82371.png)

**Comment by tmccormi** [comment]
Can someone see if this is true in current master branch please... @teryhill @aethelwulffe 
I'm testing out of my issue 55 branch

**Comment by teryhill** [comment]
Yep. But I cannot get it to run. Get errors in calendar and flow board.

**Comment by aethelwulffe** [comment]
Sorry guys.  Been doing cabinets all day.  Getting coffee and trying out:

Install and test master

Install and test #55

**Comment by teryhill** [comment]
I guess I need to do a fresh install. Blowed up Sir

**Comment by teryhill** [comment]
Just sent a fix for it

**Comment by tmccormi** [comment]
you rock.

**Comment by teryhill** [comment]
nope I caused it, only rock is in my head

**Comment by tmccormi** [comment]
Note.  if you reference the issue # in your comment comment it will like the issue to the pull ...
