### ISSUE TITLE
sql errors in issue_55_zerodates branch

### ISSUE THREAD

**Issue by htuck** [LibreEHR/LibreEHR#88]
tested links in patient summary screen, issue_55_zerodates branch; ran through the menu formerly known as 'Left Nav Menu' and opened every item.
Did not enter data to see how it was handled, just looked to see if the panel/ module opened without errors.
I'm only mentioning the modules that showed an err msg or did not open with their normal appearance.

details further below but the error messages I saw are:
- adding new encounter, when hitting save: Error: Incorrect datetime value: '' for column 'onset_date' at row 1
- adding any/ all issues, when hitting save: Error: Incorrect integer value: '' for column 'reinjury_id' at row 1
- trying to open the history link on pt record screen: 
	ERROR: insert failed: insert into history_data set pid = ?, date = NOW()
	Error: Field 'exams' doesn't have a default value
- at bottom of patient record, clicked on Amendments's Edit button
	ERROR: query failed: SELECT * FROM amendments WHERE pid = ? ORDER BY amendment_date DESC
	Error: Table 'libreehr_socrates.amendments' doesn't exist
- fees/ billing: Error: Expression #2 of ORDER BY clause is not in SELECT list, references column 'libreehr_socrates.billing.date' which is not in SELECT list; this is incompatible with DISTINCT
- all procedures screens had one or another of these:
	Error: Table 'libreehr_socrates.procedure_providers' doesn't exist
	Error: Table 'libreehr_socrates.procedure_order' doesn't exist
	Error: Table 'libreehr_socrates.procedure_result' doesn't exist
details:
>>>>>>>>>>>>>. adding new pt encounter with both the main menu 'create visit' item and the encounter list in patient record header.  Can open a new encounter panel but hit 'save amd get:
ERROR: insert failed: INSERT INTO form_encounter SET date = '2016-08-15', onset_date = '', reason = 'testy2', facility = 'Your Clinic Name Here', pc_catid = '10', facility_id = '3', billing_facility = '3', sensitivity = 'normal', referral_source = '', pid = '15168', encounter = '3', provider_id = '1'

Error: Incorrect datetime value: '' for column 'onset_date' at row 1
/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/forms/newpatient/save.php at 72:sqlInsert

>>>>>>>>>>>>>. In a new encounter panel before trying to to save it, add a new problem issue.
*** In all these issues and problem adding errors they appear when 'save' is clicked in the add problem details popup (pic)

ERROR: insert failed: INSERT INTO form_encounter SET date = '2016-08-15', onset_date = '', reason = 'test ecounter', facility = 'Your Clinic Name Here', pc_catid = '10', facility_id = '3', billing_facility = '3', sensitivity = 'normal', referral_source = '', pid = '15168', encounter = '2', provider_id = '1'

Error: Incorrect datetime value: '' for column 'onset_date' at row 1
/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/forms/newpatient/save.php at 72:sqlInsert

>>>>>>>>>>>>> new allergy issue
ERROR: insert failed: INSERT INTO lists ( date, pid, type, title, activity, comments, begdate, enddate, returndate, diagnosis, occurrence, classification, referredby, user, groupname, outcome, destination, reinjury_id, injury_grade, injury_part, injury_type, reaction, severity_al ) VALUES ( NOW(), '15168', 'allergy', 'codeine', 1, '', NULL, NULL, NULL, '', '0', '0', '', '', '', '0', '', '', '', '', '', 'unassigned', 'unassigned' )

Error: Incorrect integer value: '' for column 'reinjury_id' at row 1
/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/patient_file/summary/add_edit_issue.php at 325:sqlInsert

>>>>>>>>>>>>> attempting to open the history link on pt record screen.
ERROR: insert failed: insert into history_data set pid = ?, date = NOW()
Error: Field 'exams' doesn't have a default value

/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/library/patient.inc at 1297:sqlInsert
/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/patient_file/history/history.php at 55:newHistoryData(15168)

>>>>>>>>>>> at bottom of patient record, clicked on Amendments's Edit 
ERROR: query failed: SELECT * FROM amendments WHERE pid = ? ORDER BY amendment_date DESC
Error: Table 'libreehr_socrates.amendments' doesn't exist

/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/patient_file/summary/demographics.php at 1027:sqlStatement

running through the menu formerly known as 'left nav':

patient/ client works.
fees- payment and checkout displayed ok
	- billing showed normal upper panel; threw this in lower panel of the display:
		selected several search criteria then updated list -> no change in lower panel.

ERROR: query failed: select distinct billing.id, form_encounter.date, billing.pid, billing.code_type, billing.code, billing.user from form_encounter, billing, patient_data, claims, insurance_data where billing.encounter = form_encounter.encounter and billing.pid = form_encounter.pid and patient_data.pid = form_encounter.pid and claims.patient_id = form_encounter.pid and claims.encounter_id = form_encounter.encounter and insurance_data.pid = form_encounter.pid and insurance_data.type = 'primary' AND (billing.billed is null or billing.billed = '0' or (billing.billed = '1' and billing.bill_process = '3')) AND (form_encounter.date between '2016-08-16 00:00:00' and '2016-08-16 23:59:59') and billing.code_type like ? and billing.activity = 1 order by billing.pid, billing.date ASC

Error: Expression #2 of ORDER BY clause is not in SELECT list, references column 'libreehr_socrates.billing.date' which is not in SELECT list; this is incompatible with DISTINCT

/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/library/billrep.inc at 178:sqlStatement
/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/billing/billing_report.php at 627:getBillsListBetween(%)

fees/ posting -> blank panel below the line of tabs and screen header
fees/ batch payments -> looks normal
fees/ edi history -> looks normal
modules/ manage modules -> blank panel below the line of tabs and screen header

procedures / providers:
	ERROR: query failed: SELECT pp.* FROM procedure_providers AS pp ORDER BY pp.name

	Error: Table 'libreehr_socrates.procedure_providers' doesn't exist

	/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/orders/procedure_provider_list.php at 37:sqlStatement

procedures/ configuration looks normal
procedures/ load compendium:
	ERROR: query failed: SELECT pp.* FROM procedure_providers AS pp ORDER BY pp.name

	Error: Table 'libreehr_socrates.procedure_providers' doesn't exist

	/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/orders/procedure_provider_list.php at 37:sqlStatement

procedures/ pending review and patient results

ERROR: query failed: SELECT po.procedure_order_id, po.date_ordered, pc.procedure_order_seq, pt1.procedure_type_id AS order_type_id, pc.procedure_name, pr.procedure_report_id, pr.date_report, pr.date_collected, pr.specimen_num, pr.report_status, pr.review_status FROM procedure_order AS po JOIN procedure_order_code AS pc ON pc.procedure_order_id = po.procedure_order_id LEFT JOIN procedure_type AS pt1 ON pt1.lab_id = po.lab_id AND pt1.procedure_code = pc.procedure_code LEFT JOIN procedure_report AS pr ON pr.procedure_order_id = po.procedure_order_id AND pr.procedure_order_seq = pc.procedure_order_seq WHERE po.patient_id = '15168' AND 1 = 1 ORDER BY po.date_ordered, po.procedure_order_id, pc.procedure_order_seq, pr.procedure_report_id

Error: Table 'libreehr_socrates.procedure_order' doesn't exist

/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/orders/orders_results.php at 419:sqlStatement

procedures/ lab overview
	ERROR: query failed: SELECT DISTINCT procedure_result.result_code AS value_code FROM procedure_result JOIN procedure_report ON procedure_result.procedure_report_id = procedure_report.procedure_report_id JOIN procedure_order ON procedure_report.procedure_order_id = procedure_order.procedure_order_id WHERE procedure_order.patient_id = ? AND procedure_result.result IS NOT NULL AND procedure_result.result != ''ORDER BY procedure_result.result_code ASC

	Error: Table 'libreehr_socrates.procedure_result' doesn't exist

	/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/patient_file/summary/labdata.php at 158:sqlStatement

procedures/ batch results: opened looking normal

procedures/ electronic reports:
	ERROR: query failed: SELECT * FROM procedure_providers ORDER BY name

	Error: Table 'libreehr_socrates.procedure_providers' doesn't exist

	/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/orders/receive_hl7_results.inc.php at 1026:sqlStatement
	/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/orders/list_reports.php at 184:poll_hl7_results(Array)

**Comment by aethelwulffe** [comment]
libreehr_socrates.procedure_providers...Where did that come from?

**Comment by htuck** [comment]
closing with apologies; these have been broken out into individual issues.
- HT
