### ISSUE TITLE
sql errors separated: add a new allergy issue

### ISSUE THREAD

**Issue by htuck** [LibreEHR/LibreEHR#93]
new allergy issue
ERROR: insert failed: INSERT INTO lists ( date, pid, type, title, activity, comments, begdate, enddate, returndate, diagnosis, occurrence, classification, referredby, user, groupname, outcome, destination, reinjury_id, injury_grade, injury_part, injury_type, reaction, severity_al ) VALUES ( NOW(), '15168', 'allergy', 'codeine', 1, '', NULL, NULL, NULL, '', '0', '0', '', '', '', '0', '', '', '', '', '', 'unassigned', 'unassigned' )

Error: Incorrect integer value: '' for column 'reinjury_id' at row 1
/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/patient_file/summary/add_edit_issue.php at 325:sqlInsert

**Comment by aethelwulffe** [comment]
Drop reinjury_id from the table along with all the other soccer stuff.

**Comment by htuck** [comment]
Appears to be fixed; closing issue.
