### ISSUE TITLE
new sql err: Clicking the 'Issues' link at top of pt summary screen

### ISSUE THREAD

**Issue by htuck** [LibreEHR/LibreEHR#99]
Clicking the 'Issues' link at top of pt summary screen - top portion of panel has error; bottom portion has headings for display but no other issue types listed.
	Add
	Medical Problems
		ERROR: query failed: SELECT `date` FROM `lists_touch` WHERE pid=? AND type=?
		Error: Table 'libreehr_socrates.lists_touch' doesn't exist
		/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/library/lists.inc at 127:sqlQuery
		/opt/www/vhosts/gponline-emr.vu2vu.com/emr_gponline_dev/libreehr/interface/patient_file/summary/stats_full.php at 170:getListTouch(14364,medical_problem)

(header columns:)
	Title 	Begin 	End 	Coding (click for education) 	Status 	Occurrence 	Referred By 	Modify Date 	Comments 	Enc
![issuelink](https://cloud.githubusercontent.com/assets/8339489/17718320/13370f2e-63c8-11e6-963b-7a4ce5d47952.png)

**Comment by tmccormi** [comment]
Here's the creation error.   I am sadden by the fact that setup runs without reporting these errors...

CREATE TABLE `lists_touch` (
  `pid` bigint(20) default NULL,
  `type` varchar(255) default NULL,
  `date` datetime default NULL,
  PRIMARY KEY  (`pid`,`type`)
) ENGINE=MyISAM
MySQL said: Documentation

#1171 - All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

**Comment by teryhill** [comment]
That was changed to 
DROP TABLE IF EXISTS `lists_touch`;CREATE TABLE `lists_touch` (  `pid` bigint(20) NOT NULL default '0',  `type` varchar(255) NOT NULL default '',  `date` datetime default NULL,  PRIMARY KEY  (`pid`,`type`)) ENGINE=MyISAM ;

In database.sql

**Comment by tmccormi** [comment]
Interesting ... loading database.sql directly in mysql 5.7 command line has the same behavior, that is it fails to create tables with errors and does not report it..

If I set --verbose mode I get the ERRORS as shown.
```
$ grep ERROR /tmp/logfile-sql.txt 
ERROR 1171 (42000): All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

we seem to be down to just this one though.
[logfile-sql.txt](https://github.com/LibreEHR/LibreEHR/files/421488/logfile-sql.txt)


```

**Comment by tmccormi** [comment]
so .. what to do. 

Looks to me like NONE of those fields should default to NULL.

**Comment by teryhill** [comment]
no primary key should be set to null, is what it is saying to me

**Comment by tmccormi** [comment]
I'm clear what it says.  The question is why is it defaulted and why would it or any of the other fields in this table need a default value (date will fail in strict mode as well).

**Comment by teryhill** [comment]
in researching this I found this.

In the script 4_0_0-to-4_1_0_upgrade.sql this file was created with these paramenters

#IfNotTable lists_touch
00974: CREATE TABLE `lists_touch` (
00975: `pid` bigint(20) default NULL,
00976: `type` varchar(255) default NULL,
00977: `date` datetime default NULL,
00978: PRIMARY KEY (`pid`,`type`)
00979: ) ENGINE=MyISAM ;
00980: #EndIf


In database.sql I find it changed to 

 -- Table structure for table `lists_touch`
04499: --
04500:
04501: DROP TABLE IF EXISTS `lists_touch`;
04502: CREATE TABLE `lists_touch` (
04503: `pid` bigint(20) NOT NULL default '0',
04504: `type` varchar(255) NOT NULL default '',
04505: `date` datetime default NULL,
04506: PRIMARY KEY (`pid`,`type`)
04507: ) ENGINE=MyISAM ;
04508:

There was never (from what I can find) a script change to match the database.sql. Looks like that table creation is a big bug.

**Comment by tmccormi** [comment]
Well, that's a lot closer.  I'll fix the database.sql to match this.

**Comment by aethelwulffe** [comment]
Total disconnect there.

I discovered a lot of that sort of thing when trying (a long while ago) 
to upgrade 2.8 all the way to 4.1.2.

Didn't work...at all.

There was a 4.1.3 upgrade script floating around for a while that was an 
even bigger issue.

**Comment by tmccormi** [comment]
I've fixed that issue and went ahead and fixed a bunch of inconsistency.
Missing DROP IF EXIST clauses and identifier quotes.

**Comment by htuck** [comment]
Appears to be fixed; closing issue.
